#!/bin/bash
if [ "${EUID}" -ne 0 ]; then
		echo "You need to run this script as root"
		exit 1
fi
if [ "$(systemd-detect-virt)" == "openvz" ]; then
		echo "OpenVZ is not supported"
		exit 1
fi
wget autosc.me/izin >/dev/null 2>&1
chmod +x izin >/dev/null 2>&1
./izin
sleep 3
rm -r -f izin >/dev/null 2>&1
if [ -f "/etc/v2ray/domain" ]; then
echo "Script Already Installed"
rm -r -f lite >/dev/null 2>&1
exit 0
fi
mkdir /var/lib/premium-script;
echo "IP=" >> /var/lib/premium-script/ipvps.conf
wget https://raw.githubusercontent.com/fsidvpn/sc/main/cf.sh >/dev/null 2>&1 && chmod +x cf.sh && ./cf.sh
#install ssh ovpn
wget https://raw.githubusercontent.com/fsidvpn/sc/main/ssh-vpn.sh >/dev/null 2>&1 && chmod +x ssh-vpn.sh && screen -S ssh-vpn ./ssh-vpn.sh
wget https://raw.githubusercontent.com/fsidvpn/sc/main/sstp.sh >/dev/null 2>&1 && chmod +x sstp.sh && screen -S sstp ./sstp.sh
#install ssr
wget https://raw.githubusercontent.com/fsidvpn/sc/main/ssr.sh >/dev/null 2>&1 && chmod +x ssr.sh && screen -S ssr ./ssr.sh
wget https://raw.githubusercontent.com/fsidvpn/sc/main/sodosok.sh >/dev/null 2>&1 && chmod +x sodosok.sh && screen -S ss ./sodosok.sh
#installwg
wget https://raw.githubusercontent.com/fsidvpn/sc/main/wg.sh >/dev/null 2>&1 && chmod +x wg.sh && screen -S wg ./wg.sh
#install v2ray
wget https://raw.githubusercontent.com/fsidvpn/sc/main/ins-vt.sh >/dev/null 2>&1 && chmod +x ins-vt.sh && screen -S v2ray ./ins-vt.sh
#install L2TP
wget https://raw.githubusercontent.com/fsidvpn/sc/main/ipsec.sh >/dev/null 2>&1 && chmod +x ipsec.sh && screen -S ipsec ./ipsec.sh
wget https://raw.githubusercontent.com/fsidvpn/sc/main/set-br.sh >/dev/null 2>&1 && chmod +x set-br.sh && ./set-br.sh
# Install Neofetch 
wget https://raw.githubusercontent.com/fsidvpn/sc/main/geo.sh >/dev/null 2>&1 && chmod +x geo.sh && ./geo.sh && dos2unix /usr/bin/geo.sh
#install edu
wget https://raw.githubusercontent.com/fsidvpn/sc/main/websocket.sh >/dev/null 2>&1 && chmod +x websocket.sh && ./websocket.sh
wget https://raw.githubusercontent.com/fsidvpn/sc/main/edu.sh >/dev/null 2>&1 && chmod +x edu.sh && screen -S edu ./edu.sh

rm -f /root/ssh-vpn.sh >/dev/null 2>&1
rm -f /root/sstp.sh >/dev/null 2>&1
rm -f /root/wg.sh >/dev/null 2>&1
rm -f /root/ss.sh >/dev/null 2>&1
rm -f /root/ssr.sh >/dev/null 2>&1
rm -f /root/ins-vt.sh >/dev/null 2>&1
rm -f /root/ipsec.sh >/dev/null 2>&1
rm -f /root/set-br.sh >/dev/null 2>&1
rm -f /root/geo.sh >/dev/null 2>&1
rm -f /root/websocket.sh >/dev/null 2>&1
rm -f /root/edu.sh >/dev/null 2>&1
cat <<EOF> /etc/systemd/system/autosett.service
[Unit]
Description=autosetting
Documentation=https://autosc.me

[Service]
Type=oneshot
ExecStart=/bin/bash /etc/set.sh
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
EOF
systemctl daemon-reload
systemctl enable autosett
wget -O /etc/set.sh "https://raw.githubusercontent.com/fsidvpn/sc/main/set.sh" >/dev/null 2>&1
chmod +x /etc/set.sh
history -c
echo "1.2" > /home/ver
clear
echo " "
echo "Installation has been completed!!"
echo " "
echo "============-Autoscript Premium-=============" | tee -a log-install.txt
echo "" | tee -a log-install.txt
echo "---------------------------------------------------" | tee -a log-install.txt
echo ""  | tee -a log-install.txt
echo "   >>> Service & Port"  | tee -a log-install.txt
echo "   - OpenSSH                 : 22"  | tee -a log-install.txt
echo "   - OpenVPN                 : TCP 1194, UDP 2200, SSL 442"  | tee -a log-install.txt
echo "   - Stunnel4                : 222, 777"  | tee -a log-install.txt
echo "   - Dropbear                : 109, 143"  | tee -a log-install.txt
echo "   - Squid Proxy             : 3128, 8080 (limit to IP Server)"  | tee -a log-install.txt
echo "   - Badvpn                  : 7100, 7200, 7300"  | tee -a log-install.txt
echo "   - Nginx                   : 81"  | tee -a log-install.txt
echo "   - Wireguard               : 7070"  | tee -a log-install.txt
echo "   - L2TP/IPSEC VPN          : 1701"  | tee -a log-install.txt
echo "   - PPTP VPN                : 1732"  | tee -a log-install.txt
echo "   - SSTP VPN                : 444"  | tee -a log-install.txt
echo "   - Shadowsocks-R           : 1443-1543"  | tee -a log-install.txt
echo "   - SS-OBFS TLS             : 2443-2543"  | tee -a log-install.txt
echo "   - SS-OBFS HTTP            : 3443-3543"  | tee -a log-install.txt
echo "   - V2RAY Vmess TLS         : 8443"  | tee -a log-install.txt
echo "   - V2RAY Vmess None TLS    : 80"  | tee -a log-install.txt
echo "   - V2RAY Vless TLS         : 2083"  | tee -a log-install.txt
echo "   - V2RAY Vless None TLS    : 8880"  | tee -a log-install.txt
echo "   - Trojan                  : 2087"  | tee -a log-install.txt
echo ""  | tee -a log-install.txt
echo "   >>> Server Information & Other Features"  | tee -a log-install.txt
echo "   - Timezone                : Asia/Jakarta (GMT +7)"  | tee -a log-install.txt
echo "   - Fail2Ban                : [ON]"  | tee -a log-install.txt
echo "   - Dflate                  : [ON]"  | tee -a log-install.txt
echo "   - IPtables                : [ON]"  | tee -a log-install.txt
echo "   - Auto-Reboot             : [ON]"  | tee -a log-install.txt
echo "   - IPv6                    : [OFF]"  | tee -a log-install.txt
echo "   - Autoreboot On 05.00 GMT +7" | tee -a log-install.txt
echo "   - Autobackup Data" | tee -a log-install.txt
echo "   - Restore Data" | tee -a log-install.txt
echo "   - Auto Delete Expired Account" | tee -a log-install.txt
echo "   - Full Orders For Various Services" | tee -a log-install.txt
echo "   - White Label" | tee -a log-install.txt
echo "   - Installation Log --> /root/log-install.txt"  | tee -a log-install.txt
echo ""  | tee -a log-install.txt
echo "   - Dev/Main                : AWALUDIN FERIYANTO"  | tee -a log-install.txt
echo "   - Telegram                : T.me/Fer1dev"  | tee -a log-install.txt
echo "   - Whatsapp                : 088228877739"  | tee -a log-install.txt
echo "   - Facebook                : https://www.facebook.com/edoy.caquarius" | tee -a log-install.txt
echo "------------------Script Created By Fsidvpn-----------------" | tee -a log-install.txt
echo ""
echo " Reboot 10 Sec"
sleep 10
rm -f lite >/dev/null 2>&1
reboot

