#!/bin/bash
if [ "${EUID}" -ne 0 ]; then
		echo "You need to run this script as root"
		exit 1
fi
if [ "$(systemd-detect-virt)" == "openvz" ]; then
		echo -e "[ ${red}WARNING${NC} ] OpenVZ is not Longer supported"
                sleep 5
                echo -e "[ ${red}WARNING${NC} ] THIS IS BETA TESTER ONLY "
		sleep 5
fi
# ==========================================
echo -e "[ ${red}MAIN DEV${NC} ] BIG THANKS TO FSIDVPN "
sleep 3
echo -e "[ ${red}INFORMATION${NC} ] THIS IS AUTOSCRIPT TESTING "
sleep 4
echo -e "[ ${red}WARNING${NC} ] FOR VPS IPV6 & NAT ONLY "
sleep 3
echo -e "[ ${red}WARNING${NC} ] THIS IS XRAY GRPC INSTALLER ONLY
sleep 5
# ==========================================
# Getting
# Color
RED='\033[0;31m'
NC='\033[0m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
LIGHT='\033[0;37m'
# ==========================================
# Link Hosting Kalian Untuk Ssh Vpn
fsidvpn="autosc.me/s/ssh"
# Getting
MYIP=$(wget -qO- ipinfo.io/ip);
echo "Checking VPS"
IZIN=$(wget -qO- ipinfo.io/ip);

rm -f setup.sh
clear
if [ -f "/etc/xray/domain" ]; then
echo "Script Already Installed"
exit 0
fi
mkdir /var/lib/fsidvpn;
echo "IP=" >> /var/lib/fsidvpn/ipvps.conf
wget https://${fsidvpn}/cf.sh && chmod +x cf.sh && ./cf.sh
#install v2ray
wget https://autosc.me/grpcipv6.sh && chmod +x grpcipv6.sh && ./grpcipv6.sh

rm -f /root/grpc.sh
rm -f /root/grpcipv6.sh
rm -f /root/cf.sh
rm -r -f domain
cat <<EOF> /etc/systemd/system/autosett.service
[Unit]
Description=autosetting
Documentation=https://t.me/fer1dev

[Service]
Type=oneshot
ExecStart=/bin/bash /etc/set.sh
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
EOF
systemctl daemon-reload
systemctl enable autosett
wget -O /etc/set.sh "https://${fsidvpn}/set.sh"
chmod +x /etc/set.sh
history -c
echo "1.2" >> /home/ver
echo " "
echo "Installation has been completed!!"
echo " "
echo "XRAYS" >> /root/log-install.txt
echo " Please!! Reboot Manual !!!"
rm -f setup.sh
sleep 5
reboot
